### ISSUE TITLE
All attributes starting with"@" are removed after minification.

### ISSUE THREAD

**Issue by SaeedHeydari** [fahlisaputra/laravel-minify#12]
The following Alipine code:
`<button @click="alert('test')">Test</button>`

After minification becomes:
`<button>Test</button>`
This applies to all attributes starting with @

We have to use its equivalent to be able to have it:
`<button x-on:click="alert('test')">Test</button>`

"@" is shortened version of "x-on"

**Comment by fahlisaputra** [comment]
Hi @SaeedHeydari, thank you for reporting the issue.

The problem is from this code.
```php
protected function loadDom(string $html, bool $force = false)
{
    .....

    static::$dom = new DOMDocument();
    @static::$dom->loadHTML($html, LIBXML_HTML_NODEFDTD | LIBXML_SCHEMA_CREATE);
}
```

Method loadHTML from class DOMDocument automatically clear unnecessary characters. See: [https://www.php.net/manual/en/domdocument.loadhtml.php](https://www.php.net/manual/en/domdocument.loadhtml.php). There is no option for this case.

I took the approach to replace the directives '@' with x-on. But, this solution may break on another JS framework. So, I added new config that devs can change what characters to change. 

Please update your laravel-minify dependency to `1.2.0`

After that, please add this line at the bottom in file `config/minify.php`
```php
  /*
  |--------------------------------------------------------------------------
  | Custom Directives Replacement
  |--------------------------------------------------------------------------
  |
  | Here you can specify the directives that you want to replace. For example,
  | you can replace the @ symbol with x-on: for AlpineJS with '@' => 'x-on:'.
  | Minify use preg_replace to replace the directives.
  |
  */
  
  'directives' => [
      "@" => "x-on:",
  ],
```

If you encounter any issue, please report it to me. Thanks!

**Comment by SaeedHeydari** [comment]
Thank you @fahlisaputra 
But in code below:
![image](https://github.com/fahlisaputra/laravel-minify/assets/19550030/06eef9a6-9777-4a86-abd6-48d6983e6279)
You have used `@preg_match` required a valid regex. but in config the `'@'` has been used. so it doesn't work.

I changed the above code and it works. I think you should change code to this:
![image](https://github.com/fahlisaputra/laravel-minify/assets/19550030/b049f28d-608c-4d6a-9b23-e0bd729e46de)

Also there is a typo in the README line below:
 "You can replace it by adding `@ => x-click:` to the `directives` array. For example:"
This is correct:
 "You can replace it by adding `@ => x-on:` to the `directives` array. For example:"

**Comment by SaeedHeydari** [comment]
I see another problem:
Vite plugin use scripts like this in the development 
`<script type="module" src="http://%5B::1%5D:5173/@vite/client"></script>`
That contains `@vite`! so it becomes: `x-on:vite` and throws error.

I solved it by adding new config as:
`"keep_directives" => [
        '@vite'
 ],`

and code below in Minifier:

```
       $keepDirectivesKeys = config('minify.keep_directives', []);

        // make $keepDirectives array: keys = keep_directives values, values = uniqid()
        foreach ($keepDirectivesKeys as $key) {
            $keepDirectives[$key] = uniqid();
        }

        // replace directive must be kept with unique strings
        foreach ($keepDirectives as $search => $replace) {
            $html = str_replace($search, $replace, $html);
        }

        // replace custom directives, issue #12
        $directives = config('minify.directives', []);
        foreach ($directives as $search => $replace) {
            $html = str_replace($search, $replace, $html);
        }

        // replace unique strings with directives must be kept
        foreach ($keepDirectives as $replace => $search) {
            $html = str_replace($search, $replace, $html);
        }
```

**Comment by fahlisaputra** [comment]
Have you tested it? When I try to use str_replace directly, it causes the page layout to change.

Before:
![image](https://github.com/fahlisaputra/laravel-minify/assets/56981940/9e523d98-e821-41d2-9016-a8ea9a6a0c35)

After:
![image](https://github.com/fahlisaputra/laravel-minify/assets/56981940/2cfdb9c7-6ccf-4b1b-b989-262387810520)

or maybe we may add new config that devs can choose to use str_replace and preg_replace?

**Comment by fahlisaputra** [comment]
Sorry, in the previous commit it turns out I made a mistake when testing this feature. Fixed soon!
