### ISSUE TITLE
Warning type MIME (“text/plain”)

### ISSUE THREAD

**Issue by Laguna001** [fahlisaputra/laravel-minify#9]
Hello

The following warning appears when referencing a js file

The script “http://localhost/_minify/js/layouts/events.js” was loaded even though its type MIME (“text/plain”) is not a valid JavaScript MIME type.

Thank you for your support

**Comment by Laguna001** [comment]
$mime = preg_match("/\.js$/", $file)?"application/javascript": mime_content_type($path);

**Comment by fahlisaputra** [comment]
Thank you for reporting this issue

**Comment by fahlisaputra** [comment]
Fixed on newer version. Please let me know if any issue happens. Thank you.
